// Mirrors the response models in backend/routers/bucket3.py. Only the
// fields this prototype actually renders are declared.

export type CurrentUser = {
  id: string;
  email: string;
  username: string;
  student_profile_id: string | null;
};

export type Student = {
  id: string;
  first_name: string;
  last_name: string;
  // The district's own student id (Genesis "studentid"), which is what a
  // person actually knows - so ?student= accepts either that or the uuid.
  student_id: string;
  school_name: string | null;
};

export type TodoGrade = {
  score_earned: number | null;
  score_possible: number | null;
  percent: number | null;
  status: string | null;
};

// A "how to get started" note, generated by Haiku from the title and course
// name ONLY and cached per class - so every student in the section shares
// one, and nothing about this particular child is ever sent.
export type Suggestion = {
  text: string | null;
  declined: boolean;
};

export type SuggestionState = Suggestion & {
  loading: boolean;
  error: string | null;
};

export type TodoItem = {
  suggestion: Suggestion | null;
  id: string;
  title: string;
  item_type: string;
  course_name: string | null;
  due_raw: string | null;
  due_date: string | null;
  category: "missing" | "due" | "done" | "no_due_date";
  done: boolean;
  done_source: string | null;
  marked_by: string | null;
  classroom_status: string | null;
  grade: TodoGrade | null;
  teacher_name: string | null;
  teacher_emails: string[];
  link: string | null;
};

export type Progress = {
  done: number;
  missing: number;
  due: number;
  total: number;
  percent: number | null;
};

export type MarkingPeriod = {
  label: string;
  start_date: string;
  end_date: string;
};

export type TodoResponse = {
  current_marking_period: MarkingPeriod | null;
  progress: Progress;
  next_action: TodoItem | null;
  missing: TodoItem[];
  due: TodoItem[];
  done: TodoItem[];
  no_due_date: TodoItem[];
};

export type CourseProgress = {
  course_key: string;
  course_name: string;
  grade_percent: number | null;
  marking_period: string | null;
  total: number;
  done: number;
  missing: number;
  due_soon: number;
  completion_pct: number | null;
  teacher_name: string | null;
};

export type ScheduleBlock = {
  source: string;
  period: string;
  course_name: string;
  teacher: string | null;
  room: string | null;
  term: string | null;
  days: string | null;
  time_start: string | null;
  time_end: string | null;
};

export type ScheduleResponse = {
  cycle_date: string | null;
  cycle_label: string | null;
  daily: ScheduleBlock[];
  list_view: ScheduleBlock[];
};
