"""school documents

Revision ID: 0010
Revises: 0009
Create Date: 2026-09-08 18:39:01.270282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "0010"
down_revision: Union[str, None] = "0009"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('doc_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'doc_type', 'url', name='uq_school_document_url')
    )
    op.create_index(op.f('ix_school_documents_school_id'), 'school_documents', ['school_id'], unique=False)
    op.add_column('schools', sa.Column('documents_scan_job_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'schools', 'scheduled_jobs', ['documents_scan_job_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schools', type_='foreignkey')
    op.drop_column('schools', 'documents_scan_job_id')
    op.drop_index(op.f('ix_school_documents_school_id'), table_name='school_documents')
    op.drop_table('school_documents')
    # ### end Alembic commands ###
