"""sacc programs

Revision ID: 0011
Revises: 0010
Create Date: 2026-09-08 19:02:10.491639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "0011"
down_revision: Union[str, None] = "0010"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sacc_programs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('am_hours', sa.String(length=100), nullable=True),
    sa.Column('pm_hours', sa.String(length=100), nullable=True),
    sa.Column('site_phone', sa.String(length=50), nullable=True),
    sa.Column('absence_phone', sa.String(length=50), nullable=True),
    sa.Column('absence_form_url', sa.String(length=500), nullable=True),
    sa.Column('late_pickup_policy', sa.String(), nullable=True),
    sa.Column('pickup_change_procedure', sa.String(), nullable=True),
    sa.Column('closures_notes', sa.String(), nullable=True),
    sa.Column('handbook_url', sa.String(length=1000), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sacc_programs')
    # ### end Alembic commands ###
