"""school info scan

Revision ID: 0012
Revises: 0011
Create Date: 2026-09-08 20:13:17.336761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "0012"
down_revision: Union[str, None] = "0011"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('school_info_job_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'schools', 'scheduled_jobs', ['school_info_job_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schools', type_='foreignkey')
    op.drop_column('schools', 'school_info_job_id')
    # ### end Alembic commands ###
