"""email scanner school id

Revision ID: 0013
Revises: 0012
Create Date: 2026-09-08 20:43:26.028107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "0013"
down_revision: Union[str, None] = "0012"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_scanners', sa.Column('school_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'email_scanners', 'schools', ['school_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'email_scanners', type_='foreignkey')
    op.drop_column('email_scanners', 'school_id')
    # ### end Alembic commands ###
