"""absence portal

Revision ID: 0014
Revises: 0013
Create Date: 2026-09-08 20:47:09.050112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "0014"
down_revision: Union[str, None] = "0013"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('absence_portal_name', sa.String(length=100), nullable=True))
    op.add_column('schools', sa.Column('absence_portal_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schools', 'absence_portal_url')
    op.drop_column('schools', 'absence_portal_name')
    # ### end Alembic commands ###
