"""district calendar feed

Revision ID: 0015
Revises: 0014
Create Date: 2026-09-08 21:06:44.815273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "0015"
down_revision: Union[str, None] = "0014"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('districts', sa.Column('calendar_ics_url', sa.String(length=1000), nullable=True))
    op.add_column('districts', sa.Column('calendar_scan_job_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'districts', 'scheduled_jobs', ['calendar_scan_job_id'], ['id'], ondelete='SET NULL')
    # server_default backfills existing rows (all previously from newsletter
    # extraction) - matches the model's Python-side default for new rows.
    op.add_column('school_content_items', sa.Column('source', sa.String(length=20), nullable=False, server_default='newsletter'))
    op.alter_column('school_content_items', 'source', server_default=None)
    op.add_column('school_content_items', sa.Column('external_uid', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_school_content_items_external_uid'), 'school_content_items', ['external_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_school_content_items_external_uid'), table_name='school_content_items')
    op.drop_column('school_content_items', 'external_uid')
    op.drop_column('school_content_items', 'source')
    op.drop_constraint(None, 'districts', type_='foreignkey')
    op.drop_column('districts', 'calendar_scan_job_id')
    op.drop_column('districts', 'calendar_ics_url')
    # ### end Alembic commands ###
