"""multi ics feeds and marking period

Revision ID: 0016
Revises: 0015
Create Date: 2026-09-08 21:16:17.143468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "0016"
down_revision: Union[str, None] = "0015"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('districts', sa.Column('ics_feeds', sa.JSON(), nullable=False, server_default='[]'))
    op.alter_column('districts', 'ics_feeds', server_default=None)
    op.add_column('districts', sa.Column('marking_period_url', sa.String(length=1000), nullable=True))
    op.add_column('districts', sa.Column('marking_period_job_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'districts', 'scheduled_jobs', ['marking_period_job_id'], ['id'], ondelete='SET NULL')
    op.drop_column('districts', 'calendar_ics_url')
    op.add_column('school_content_items', sa.Column('applies_to_school_types', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school_content_items', 'applies_to_school_types')
    op.add_column('districts', sa.Column('calendar_ics_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'districts', type_='foreignkey')
    op.drop_column('districts', 'marking_period_job_id')
    op.drop_column('districts', 'marking_period_url')
    op.drop_column('districts', 'ics_feeds')
    # ### end Alembic commands ###
