"""preschool locations and team

Revision ID: 0017
Revises: 0016
Create Date: 2026-09-08 21:22:34.461154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "0017"
down_revision: Union[str, None] = "0016"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('districts', sa.Column('preschool_locations_url', sa.String(length=1000), nullable=True))
    op.add_column('districts', sa.Column('preschool_locations_job_id', sa.String(length=36), nullable=True))
    op.add_column('districts', sa.Column('preschool_team_url', sa.String(length=1000), nullable=True))
    op.add_column('districts', sa.Column('preschool_team_job_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'districts', 'scheduled_jobs', ['preschool_locations_job_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'districts', 'scheduled_jobs', ['preschool_team_job_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'districts', type_='foreignkey')
    op.drop_constraint(None, 'districts', type_='foreignkey')
    op.drop_column('districts', 'preschool_team_job_id')
    op.drop_column('districts', 'preschool_team_url')
    op.drop_column('districts', 'preschool_locations_job_id')
    op.drop_column('districts', 'preschool_locations_url')
    # ### end Alembic commands ###
