"""school slug and school-scoped lunch menu

Revision ID: 0018
Revises: 0017
Create Date: 2026-09-08 22:50:23.375914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "0018"
down_revision: Union[str, None] = "0017"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lunch_menus', sa.Column('school_id', sa.String(length=36), nullable=True))
    op.alter_column('lunch_menus', 'district_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('lunch_menus', 'school_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_foreign_key(None, 'lunch_menus', 'schools', ['school_id'], ['id'], ondelete='CASCADE')

    # Nullable first so existing rows can be backfilled deterministically
    # from short_name/name before the NOT NULL + unique constraints land.
    op.add_column('schools', sa.Column('slug', sa.String(length=150), nullable=True))
    op.execute("UPDATE schools SET slug = lower(regexp_replace(coalesce(short_name, name), '[^a-zA-Z0-9]+', '-', 'g'))")
    op.execute("UPDATE schools SET slug = trim(both '-' from slug)")
    op.execute("UPDATE schools SET slug = 'school-' || substr(id, 1, 8) WHERE slug IS NULL OR slug = ''")
    op.execute(
        """
        WITH ranked AS (
            SELECT id, slug, row_number() OVER (PARTITION BY slug ORDER BY created_at) AS rn
            FROM schools
        )
        UPDATE schools s SET slug = ranked.slug || '-' || ranked.rn
        FROM ranked WHERE s.id = ranked.id AND ranked.rn > 1
        """
    )
    op.alter_column('schools', 'slug', nullable=False)
    op.create_unique_constraint(None, 'schools', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schools', type_='unique')
    op.drop_column('schools', 'slug')
    op.drop_constraint(None, 'lunch_menus', type_='foreignkey')
    op.alter_column('lunch_menus', 'school_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('lunch_menus', 'district_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('lunch_menus', 'school_id')
    # ### end Alembic commands ###
