// Mirrors the response models in backend/routers/bucket3.py. Only the
// fields this prototype actually renders are declared.

export type CurrentUser = {
  id: string;
  email: string;
  username: string;
  student_profile_id: string | null;
};

export type Student = {
  id: string;
  first_name: string;
  last_name: string;
  // The district's own student id (Genesis "studentid"), which is what a
  // person actually knows - so ?student= accepts either that or the uuid.
  student_id: string;
  school_name: string | null;
};

export type TodoGrade = {
  score_earned: number | null;
  score_possible: number | null;
  percent: number | null;
  status: string | null;
};

// A "how to get started" note, generated by Haiku from the title and course
// name ONLY and cached per class - so every student in the section shares
// one, and nothing about this particular child is ever sent.
export type Suggestion = {
  text: string | null;
  declined: boolean;
};

export type SuggestionState = Suggestion & {
  loading: boolean;
  error: string | null;
};

// What this class's late policy says is still earnable on one item. Null on
// the item when no policy is on file - "we don't know" stays distinct from
// "we know it's zero", and only the second one is allowed to change what the
// dashboard shows.
export type LateCredit = {
  accepted: boolean;
  credit_pct: number | null;
  closes_on: string | null;
  days_left: number | null;
  is_late: boolean;
  extension_by_request: boolean;
  // True when a teacher's own exception produced this, not the class rule.
  by_exception: boolean;
};

/** "Turn it in by the 6th and I'll take it." Overrides the class policy for
 * this one assignment, and outranks the marking-period filter - a human
 * grant beats every rule the app applies on its own. */
export type LateException = {
  accepted_until: string;
  credit_pct: number | null;
  granted_note: string | null;
};

export type HelpKind = { kind: string; label: string };

export type HelpDraft = {
  kind: string;
  label: string;
  subject: string;
  body: string;
  teacher_email: string | null;
};

export type LatePolicy = {
  course_key: string;
  course_name: string | null;
  shape: "full_credit" | "flat" | "daily_decay" | "window" | "tiered" | "not_accepted";
  penalty_pct: number | null;
  penalty_per_day: number | null;
  floor_pct: number | null;
  window_days: number | null;
  steps: { days: number; credit_pct: number }[] | null;
  accepted_until: string | null;
  applies_to_types: string[] | null;
  extension_by_request: boolean;
  source_text: string | null;
  notes: string | null;
};

export type LatePolicyParse = {
  understood: boolean;
  summary: string | null;
  source_sentence: string | null;
  policy: Partial<LatePolicy> | null;
};

export type TodoItem = {
  suggestion: Suggestion | null;
  late_credit: LateCredit | null;
  late_exception: LateException | null;
  asked_kinds: string[];
  id: string;
  title: string;
  item_type: string;
  course_name: string | null;
  // Same identity CourseProgress.course_key uses - lets Focus and Subjects
  // key a class's color off the same thing rather than disagreeing.
  course_key: string;
  due_raw: string | null;
  due_date: string | null;
  category: "missing" | "due" | "done" | "no_due_date";
  done: boolean;
  done_source: string | null;
  marked_by: string | null;
  classroom_status: string | null;
  grade: TodoGrade | null;
  // From the assignment's own detail page, not the classwork/stream card
  // this item is otherwise built from - null means "not captured yet",
  // never "worth zero".
  points_possible: number | null;
  teacher_name: string | null;
  teacher_emails: string[];
  link: string | null;
};

export type Progress = {
  done: number;
  missing: number;
  due: number;
  total: number;
  percent: number | null;
};

export type MarkingPeriod = {
  label: string;
  start_date: string;
  end_date: string;
};

export type TodoResponse = {
  current_marking_period: MarkingPeriod | null;
  progress: Progress;
  next_action: TodoItem | null;
  missing: TodoItem[];
  due: TodoItem[];
  done: TodoItem[];
  no_due_date: TodoItem[];
};

export type CourseProgress = {
  course_key: string;
  course_name: string;
  grade_percent: number | null;
  marking_period: string | null;
  total: number;
  done: number;
  missing: number;
  due_soon: number;
  completion_pct: number | null;
  teacher_name: string | null;
  teacher_emails: string[];
};

export type ScheduleBlock = {
  source: string;
  period: string;
  schedule_date: string | null;
  course_name: string;
  teacher: string | null;
  room: string | null;
  term: string | null;
  days: string | null;
  time_start: string | null;
  time_end: string | null;
};

export type ScheduleResponse = {
  cycle_date: string | null;
  cycle_label: string | null;
  daily: ScheduleBlock[];
  list_view: ScheduleBlock[];
  days?: ScheduleDay[];
};

export type ScheduleDayBlock = {
  name: string;
  start_label: string | null;
  end_label: string | null;
  course_name: string | null;
  teacher: string | null;
  room: string | null;
};

export type ScheduleDay = {
  date: string;
  weekday: string;
  status: string;
  rotation_day: string | null;
  long_blocks: boolean;
  timed: boolean;
  blocks: ScheduleDayBlock[];
};
